@HostAddress = http://localhost:5098

### agent request
POST {{HostAddress}}/agent/
Accept: application/json
Content-Type: application/json

{
  "prompt": "Мне нужно полное имя мужчины с сайта https://randomuser.me/api"
}


### get version
GET {{HostAddress}}/version
Accept: application/json


### get test
GET {{HostAddress}}/test
Accept: application/json
